//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/sebastian/studia/inf/8/jfk/proj/Polski/Polski.Compiler/LanguageDefinition/Polski.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PolskiParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IPolskiVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] PolskiParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] PolskiParser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] PolskiParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclaration([NotNull] PolskiParser.FunctionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.functionBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionBlock([NotNull] PolskiParser.FunctionBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] PolskiParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf([NotNull] PolskiParser.IfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile([NotNull] PolskiParser.WhileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] PolskiParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint([NotNull] PolskiParser.PrintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.read"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRead([NotNull] PolskiParser.ReadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.booleanOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanOrExpression([NotNull] PolskiParser.BooleanOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.booleanAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanAndExpression([NotNull] PolskiParser.BooleanAndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.booleanXorExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanXorExpression([NotNull] PolskiParser.BooleanXorExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.booleanPrimaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanPrimaryExpression([NotNull] PolskiParser.BooleanPrimaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.booleanValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanValue([NotNull] PolskiParser.BooleanValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] PolskiParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] PolskiParser.AdditiveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpression([NotNull] PolskiParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] PolskiParser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpression([NotNull] PolskiParser.PrimaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] PolskiParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] PolskiParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.globalDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalDefinition([NotNull] PolskiParser.GlobalDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefinition([NotNull] PolskiParser.DefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] PolskiParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] PolskiParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PolskiParser.numericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericType([NotNull] PolskiParser.NumericTypeContext context);
}
