//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Projects/compiler/Polski/Polski.Compiler/LanguageDefinition/Polski.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PolskiParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IPolskiListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PolskiParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] PolskiParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PolskiParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] PolskiParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PolskiParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] PolskiParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PolskiParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] PolskiParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PolskiParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] PolskiParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PolskiParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] PolskiParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PolskiParser.printStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintStatement([NotNull] PolskiParser.PrintStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PolskiParser.printStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintStatement([NotNull] PolskiParser.PrintStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PolskiParser.readStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReadStatement([NotNull] PolskiParser.ReadStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PolskiParser.readStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReadStatement([NotNull] PolskiParser.ReadStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PolskiParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] PolskiParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PolskiParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] PolskiParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PolskiParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] PolskiParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PolskiParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] PolskiParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PolskiParser.arithmeticExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmeticExpression([NotNull] PolskiParser.ArithmeticExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PolskiParser.arithmeticExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmeticExpression([NotNull] PolskiParser.ArithmeticExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PolskiParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] PolskiParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PolskiParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] PolskiParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PolskiParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] PolskiParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PolskiParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] PolskiParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PolskiParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinition([NotNull] PolskiParser.DefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PolskiParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinition([NotNull] PolskiParser.DefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PolskiParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] PolskiParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PolskiParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] PolskiParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PolskiParser.numericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericType([NotNull] PolskiParser.NumericTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PolskiParser.numericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericType([NotNull] PolskiParser.NumericTypeContext context);
}
