name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_NAME: Polski

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore ${{ env.SOLUTION_NAME }}
      
    - name: Build project
      run: dotnet build ${{ env.SOLUTION_NAME }}
      
    - name: Run tests
      run: dotnet test ${{ env.SOLUTION_NAME }}
